### ISSUE TITLE
musicbrainz-client tests flaky in full suite: 503 backoff bleeds across tests (getArtistOrigin timeout + tracklist order shift)

### ISSUE THREAD

**Issue by kevinch3** [kevinch3/NicotinD#541]
Seen on master at a7940167 (artist-origin merge), reproduced twice in a row with `bun run test`; both tests **pass in isolation** (`bun test packages/api/src/services/musicbrainz-client.test.ts` → 22 pass).

Full-suite failures:

- `MusicBrainzClient getArtistOrigin > reports a transient failure as ok:false and does not cache it` — times out at exactly **5000.06ms**, right after the log line `MusicBrainz 503 — backing off 5s` for its own `artist/mbid-4` request. Under full-suite timing the real-timer 5s backoff (plus rate-limit contention from neighboring tests) pushes the test past bun's 5s default timeout.
- `MusicBrainzClient getCanonicalTracklist > prefers the Official release with the most tracks, not the first listed` — `expect(calls[1]).toContain('/release/full')` fails because `calls[1]` is undefined: the backoff/rate-limit delay shifts the request order recorded by the fake fetch.

Likely fix direction: inject a clock/sleep into `MusicBrainzClient`'s backoff (the same injectable style `DiscogsClient` already uses), or reset/scope the backoff state per instance in tests, so no test ever sits on a real 5s sleep. Related guard: `bun run check:isolated-specs` covers the inverse case (passes-only-in-suite) but nothing catches fails-only-in-suite.

Unrelated to #539 (found while running `bun run verify` for that fix).
